export const saludos = [
  "hola", "buenas", "buen día", "buenas tardes", "buenas noches", "qué tal",
  "saludos", "mucho gusto", "un placer", "muy buenas",
  "holaaa", "holi", "hey", "ey", "eyyy", "qué onda", "qué ondas", "qué hay",
  "qué pasa", "qué tal bro", "qué tal amiga", "qué más", "qué hubo", "qué hubo bro",
  "qué hubo amiga", "hola hola", "holis", "hola bro", "hola amiga", "holi bro",
  "holi amiga", "holiwis", "holiwi", "holi 😄", "holaaa 😎", "qué onda 😎", "hey bro",
  "hey amiga", "hey hey", "hii", "heyy", "hola! 😁", "hola!!", "holaa!!", "holaaa!!",
  "ey bro", "ey amiga", "hi", "hello", "hola uwu", "holi uwu", "hola xD", "holi xD",
  "holi :3", "holaa :3", "holi hehe", "holaaa hehe", "qué onda uwu", "qué ondas uwu",
  "hey uwu", "ey uwu", "qué tal uwu", "heyyy", "holaaah", "holaaah 😎", "holaaaa 😎",
  "holaaa 😜", "holi 😜", "qué onda 😜", "qué tal 😎", "hola q tal", "holi q tal",
  "ey qué tal", "hey qué tal", "holi bro 😎", "holi amiga 😎", "qué pasa bro",
  "qué pasa amiga", "ey qué onda", "ey qué ondas", "qué más bro", "qué más amiga",
  "que ondas", "qué ondas 😎", "qué onda bro", "qué onda amiga", "qué onda mae",
  "qué ondas mae", "qué más mae", "qué tal mae", "ey mae", "eyyy mae", "hola mae",
  "holi mae", "holaa mae", "hey mae", "hii mae", "heyy mae", "hola hola mae",
  "holi bro mae", "holi amiga mae", "qué hubo mae", "qué hubo bro mae",
  "qué hubo amiga mae", "qué onda vos", "qué tal vos", "hola vos", "holi vos",
  "qué pasa vos", "qué hubo vos", "mae qué onda", "mae hola", "mae holi",
  "hola mae 😎", "holi mae 😄", "ey mae 😎", "qué onda mae 😜", "qué tal mae 😎",
  "holaaa pura vida", "holi pura vida", "pura vida bro", "pura vida amiga",
  "pura vida mae", "pura vida", "pura vida ✌️", "holaa ✌️", "holi ✌️",
  "qué ondas bro", "qué ondas amiga", "qué ondas mae 😎", "qué onda mae 😄",
  "qué más bro 😎", "qué más amiga 😎", "holaa xD", "holi xD", "holaa :3", "holi :3",
  "ey qué más", "ey qué más bro", "ey qué más amiga", "hey qué más", "hey qué más bro",
  "hey qué más amiga", "hola bro 😎", "hola amiga 😎", "holi bro 😄", "holi amiga 😄",
  "qué hay bro", "qué hay amiga", "qué hay mae", "qué hay mae 😎", "qué hay 😎",
  "qué hubo bro 😎", "qué hubo amiga 😎", "qué hubo mae 😄", "holis bro", "holis amiga",
  "holis mae", "holis ✌️", "hola bro ✌️", "hola amiga ✌️", "hola mae ✌️", "ey bro 😎",
  "ey amiga 😎", "ey mae 😄",
  "qué papi cómo está", "qué tuanis", "qué flow", "qué onda man", "qué onda man 😎",
  "qué onda papi", "qué hay papi", "qué hubo papi", "hola papi", "holi papi",
  "qué más papi", "qué más bro 😜", "ey bro 😜", "hey bro 😜", "holi bro 😜", "holaaa bro 😜", "mi viejo"
];
